<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:isyelk="http://www.universal-devices.com/wsdk/isy/elk/1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="udi" targetNamespace="http://www.universal-devices.com/wsdk/isy/elk/1.0">
      <wsdl:documentation>
    	 Copyright 2007/2012 Universal Devices, Inc.
    	 All Rights Reserved

   		 Web Services Flag, Objects, Parameters, Messages, and Bindings for ISY 
    	 WebService Port/Binding for ISY
      </wsdl:documentation> 
     <wsdl:import
     	namespace="http://www.universal-devices.com/wsdk/isy/elk/1.0"
     	location="udielkws1.wsdl">
     </wsdl:import>
     <wsdl:service name="UDIELKWebServices">
    	<wsdl:port name="UDIELKWebServices_Port" binding="isyelk:UDIELKWebServices_Binding">
    		<wsdl:documentation>UDIServices defines the Port to which all UDI Services should be POSTED</wsdl:documentation>
    		<soap:address location="http://192.168.0.195:8080/services/elk" />
    	</wsdl:port>
    </wsdl:service>
</wsdl:definitions>