#!/opt/local/bin/python3.3
import argparse
import fileinput
import sys
import glob
import os

def fix_image_set(image_set):
    print(image_set)

def process_directories(directory):
    directories = glob.glob(directory+'/*')
    for d in directories:
        if d.endswith('imageset'):
            fix_image_set(d)
        else:
            subdirectories = glob.glob(d + '/*')
            for subdirectory in subdirectories:
                process_directories(subdirectory)

parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument('xcassets', help="Path to Xcode assets to fix")
args = parser.parse_args()


process_directories(args.xcassets)
