//
// RemoteElement+Accessors
// Remote
//
// Created by Jason Cardwell on 2/9/13.
// Copyright (c) 2013 Moondeer Studios. All rights reserved.
//
#import "RemoteElement_Private.h"

/**
 * Implemented to replace the possibly broken NSSet accessors generated by Core Data
 */
@implementation RemoteElement (ConstraintAccessors)

/*
- (NSSet *)subelementConstraints {
    return self.layoutConfiguration.subelementConstraints;
}

- (NSSet *)dependentConstraints {
    return self.layoutConfiguration.dependentConstraints;
}

- (NSSet *)dependentChildConstraints {
    return self.layoutConfiguration.dependentChildConstraints;
}

- (NSSet *)dependentSiblingConstraints {
    return self.layoutConfiguration.dependentSiblingConstraints;
}

- (NSSet *)intrinsicConstraints {
    return self.layoutConfiguration.intrinsicConstraints;
}
*/

MSKIT_STATIC_STRING_CONST kConstraintsKey           = @"contraints";
MSKIT_STATIC_STRING_CONST kFirstItemConstraintsKey  = @"firstItemConstraints";
MSKIT_STATIC_STRING_CONST kSecondItemConstraintsKey = @"secondItemContraints";

- (void)addConstraint:(REConstraint *)constraint {
    assert(constraint);
    //TODO: Still not sure if owner should be set here or in constraint initializer
    constraint.owner = self;
    [self addConstraintsObject:constraint];
}

- (void)removeConstraint:(REConstraint *)constraint {
    [self removeConstraintsObject:constraint];
    
    [self.managedObjectContext performBlockAndWait:^{
        [self.managedObjectContext deleteObject:constraint];
    }];
}

- (void)addConstraintsObject:(REConstraint *)constraint
{
    NSSet * values = [NSSet setWithObject:constraint];

    [self willChangeValueForKey:kConstraintsKey
                withSetMutation:NSKeyValueUnionSetMutation
                   usingObjects:values];

    [self.primitiveConstraints addObject:constraint];

    [self didChangeValueForKey:kConstraintsKey
               withSetMutation:NSKeyValueUnionSetMutation
                  usingObjects:values];
}

- (void)removeConstraintsObject:(REConstraint *)constraint
{
    NSSet * values = [NSSet setWithObject:constraint];

    [self willChangeValueForKey:kConstraintsKey
                withSetMutation:NSKeyValueMinusSetMutation
                   usingObjects:values];

    [self.primitiveConstraints minusSet:values];

    [self didChangeValueForKey:kConstraintsKey
               withSetMutation:NSKeyValueMinusSetMutation
                  usingObjects:values];
    
}

- (void)addConstraints:(NSSet *)constraints
{
    for (REConstraint * constraint in constraints)
        [self addConstraint:constraint];
}

- (void)removeConstraints:(NSSet *)constraints
{
    for (REConstraint * constraint in constraints)
        [self removeConstraint:constraint];
}

- (void)addFirstItemConstraintsObject:(REConstraint *)constraint
{
    NSSet * values = [NSSet setWithObject:constraint];

    [self willChangeValueForKey:kFirstItemConstraintsKey
                withSetMutation:NSKeyValueUnionSetMutation
                   usingObjects:values];

    [self.primitiveFirstItemConstraints unionSet:values];

    [self didChangeValueForKey:kFirstItemConstraintsKey
               withSetMutation:NSKeyValueUnionSetMutation
                  usingObjects:values];
}

- (void)removeFirstItemConstraintsObject:(REConstraint *)constraint
{
    NSSet * values = [NSSet setWithObject:constraint];

    [self willChangeValueForKey:kFirstItemConstraintsKey
                withSetMutation:NSKeyValueMinusSetMutation
                   usingObjects:values];

    [self.primitiveFirstItemConstraints minusSet:values];

    [self didChangeValueForKey:kFirstItemConstraintsKey
               withSetMutation:NSKeyValueMinusSetMutation
                  usingObjects:values];
}

- (void)addFirstItemConstraints:(NSSet *)constraints
{
    [self willChangeValueForKey:kFirstItemConstraintsKey
                withSetMutation:NSKeyValueUnionSetMutation
                   usingObjects:constraints];

    [self.primitiveFirstItemConstraints unionSet:constraints];

    [self didChangeValueForKey:kFirstItemConstraintsKey
               withSetMutation:NSKeyValueUnionSetMutation
                  usingObjects:constraints];
}

- (void)removeFirstItemConstraints:(NSSet *)constraints
{
    [self willChangeValueForKey:kFirstItemConstraintsKey
                withSetMutation:NSKeyValueMinusSetMutation
                   usingObjects:constraints];

    [self.primitiveFirstItemConstraints minusSet:constraints];

    [self didChangeValueForKey:kFirstItemConstraintsKey
               withSetMutation:NSKeyValueMinusSetMutation
                  usingObjects:constraints];
}

- (void)addSecondItemConstraintsObject:(REConstraint *)constraint
{
    NSSet * values = [NSSet setWithObject:constraint];

    [self willChangeValueForKey:kSecondItemConstraintsKey
                withSetMutation:NSKeyValueUnionSetMutation
                   usingObjects:values];

    [self.primitiveSecondItemConstraints unionSet:values];

    [self didChangeValueForKey:kSecondItemConstraintsKey
               withSetMutation:NSKeyValueUnionSetMutation
                  usingObjects:values];
}

- (void)removeSecondItemConstraintsObject:(REConstraint *)constraint
{
    NSSet * values = [NSSet setWithObject:constraint];

    [self willChangeValueForKey:kSecondItemConstraintsKey
                withSetMutation:NSKeyValueMinusSetMutation
                   usingObjects:values];

    [self.primitiveSecondItemConstraints minusSet:values];

    [self didChangeValueForKey:kSecondItemConstraintsKey
               withSetMutation:NSKeyValueMinusSetMutation
                  usingObjects:values];
}

- (void)addSecondItemConstraints:(NSSet *)constraints
{
    [self willChangeValueForKey:kSecondItemConstraintsKey
                withSetMutation:NSKeyValueUnionSetMutation
                   usingObjects:constraints];

    [self.primitiveSecondItemConstraints unionSet:constraints];

    [self didChangeValueForKey:kSecondItemConstraintsKey
               withSetMutation:NSKeyValueUnionSetMutation
                  usingObjects:constraints];
}

- (void)removeSecondItemConstraints:(NSSet *)constraints
{
    [self willChangeValueForKey:kSecondItemConstraintsKey
                withSetMutation:NSKeyValueMinusSetMutation
                   usingObjects:constraints];

    [self.primitiveSecondItemConstraints minusSet:constraints];

    [self didChangeValueForKey:kSecondItemConstraintsKey
               withSetMutation:NSKeyValueMinusSetMutation
                  usingObjects:constraints];
}

@end

/**
 * Implemented to replace the broken NSOrderedSet accessors generated by Core Data
 */
@implementation RemoteElement (SubelementsAccessors)

MSKIT_STATIC_STRING_CONST kSubelementsKey = @"subelements";

- (void)insertObject:(RemoteElement *)value inSubelementsAtIndex:(NSUInteger)idx {
    NSIndexSet * indexes = [NSIndexSet indexSetWithIndex:idx];

    [self willChange:NSKeyValueChangeInsertion valuesAtIndexes:indexes forKey:kSubelementsKey];
    [[self primitiveValueForKey:kSubelementsKey] insertObject:value atIndex:idx];
    [self didChange:NSKeyValueChangeInsertion valuesAtIndexes:indexes forKey:kSubelementsKey];
}

- (void)removeObjectFromSubelementsAtIndex:(NSUInteger)idx {
    NSIndexSet * indexes = [NSIndexSet indexSetWithIndex:idx];

    [self willChange:NSKeyValueChangeRemoval valuesAtIndexes:indexes forKey:kSubelementsKey];
    [[self primitiveValueForKey:kSubelementsKey] removeObjectAtIndex:idx];
    [self didChange:NSKeyValueChangeRemoval valuesAtIndexes:indexes forKey:kSubelementsKey];
}

- (void)insertSubelements:(NSArray *)values atIndexes:(NSIndexSet *)indexes {
    [self willChange:NSKeyValueChangeInsertion valuesAtIndexes:indexes forKey:kSubelementsKey];
    [[self primitiveValueForKey:kSubelementsKey] insertObjects:values atIndexes:indexes];
    [self didChange:NSKeyValueChangeInsertion valuesAtIndexes:indexes forKey:kSubelementsKey];
}

- (void)removeSubelementsAtIndexes:(NSIndexSet *)indexes {
    [self willChange:NSKeyValueChangeRemoval valuesAtIndexes:indexes forKey:kSubelementsKey];
    [[self primitiveValueForKey:kSubelementsKey] removeObjectsAtIndexes:indexes];
    [self didChange:NSKeyValueChangeRemoval valuesAtIndexes:indexes forKey:kSubelementsKey];
}

- (void)replaceObjectInSubelementsAtIndex:(NSUInteger)idx withObject:(RemoteElement *)value {
    NSIndexSet * indexes = [NSIndexSet indexSetWithIndex:idx];

    [self willChange:NSKeyValueChangeReplacement valuesAtIndexes:indexes forKey:kSubelementsKey];
    [self primitiveValueForKey:kSubelementsKey][idx] = value;
    [self didChange:NSKeyValueChangeReplacement valuesAtIndexes:indexes forKey:kSubelementsKey];
}

- (void)replaceSubelementsAtIndexes:(NSIndexSet *)indexes withSubelements:(NSArray *)values {
    [self willChange:NSKeyValueChangeReplacement valuesAtIndexes:indexes forKey:kSubelementsKey];
    [[self primitiveValueForKey:kSubelementsKey] replaceObjectsAtIndexes:indexes withObjects:values];
    [self didChange:NSKeyValueChangeReplacement valuesAtIndexes:indexes forKey:kSubelementsKey];
}

- (void)addSubelementsObject:(RemoteElement *)value {
    NSUInteger   idx     = [[self primitiveValueForKey:kSubelementsKey] count];
    NSIndexSet * indexes = [NSIndexSet indexSetWithIndex:idx];

    [self willChange:NSKeyValueChangeInsertion valuesAtIndexes:indexes forKey:kSubelementsKey];
    [[self primitiveValueForKey:kSubelementsKey] addObject:value];
    [self didChange:NSKeyValueChangeInsertion valuesAtIndexes:indexes forKey:kSubelementsKey];
}

- (void)removeSubelementsObject:(RemoteElement *)value {
    NSUInteger   idx = [[self primitiveValueForKey:kSubelementsKey] indexOfObject:value];

    if (idx != NSNotFound) {
        NSIndexSet * indexes = [NSIndexSet indexSetWithIndex:idx];

        [self willChange:NSKeyValueChangeRemoval valuesAtIndexes:indexes forKey:kSubelementsKey];
        [[self primitiveValueForKey:kSubelementsKey] removeObject:value];
        [self didChange:NSKeyValueChangeRemoval valuesAtIndexes:indexes forKey:kSubelementsKey];
    }
}

- (void)addSubelements:(NSOrderedSet *)values {
    NSMutableIndexSet * indexes      = [NSMutableIndexSet indexSet];
    NSUInteger          valuesCount  = [values count];
    NSUInteger          objectsCount = [[self primitiveValueForKey:kSubelementsKey] count];

    for (NSUInteger i = 0; i < valuesCount; ++i) {
        [indexes addIndex:(objectsCount + i)];
    }

    if (valuesCount > 0) {
        [self willChange:NSKeyValueChangeInsertion valuesAtIndexes:indexes forKey:kSubelementsKey];
        [[self primitiveValueForKey:kSubelementsKey] addObjectsFromArray:[values array]];
        [self didChange:NSKeyValueChangeInsertion valuesAtIndexes:indexes forKey:kSubelementsKey];
    }
}

- (void)removeSubelements:(NSOrderedSet *)values {
    NSMutableIndexSet * indexes = [NSMutableIndexSet indexSet];

    for (id value in values) {
        NSUInteger   idx = [[self primitiveValueForKey:kSubelementsKey] indexOfObject:value];

        if (idx != NSNotFound) [indexes addIndex:idx];
    }

    if ([indexes count] > 0) {
        [self willChange:NSKeyValueChangeRemoval valuesAtIndexes:indexes forKey:kSubelementsKey];
        [[self primitiveValueForKey:kSubelementsKey] removeObjectsAtIndexes:indexes];
        [self didChange:NSKeyValueChangeRemoval valuesAtIndexes:indexes forKey:kSubelementsKey];
    }
}

@end
