//
//  NamedModelObject+Bank.swift
//  Remote
//
//  Created by Jason Cardwell on 5/17/15.
//  Copyright (c) 2014 Moondeer Studios. All rights reserved.
//

import Foundation
import DataModel
import CoreData
import MoonKit

extension NamedModelObject {

  /**
  nameFormFieldTemplate:

  - parameter #context: NSManagedObjectContext

  - returns: FieldTemplate
  */
  static func nameFormFieldTemplate(context context: NSManagedObjectContext) -> Field.Template {
    let entity = " ".join(entityDescription.name!.split(~/"(?=\\p{Lu}\\p{Ll})"))
    let placeholder = "The \(entity)'s name"
    let validation: (String?) -> Bool = {
      !($0 == nil   ||
        $0!.isEmpty ||
        self.countInContext(context, predicate: ∀"name == '\($0)' OR autoGeneratedName == '\($0)'") > 0)
    }
    return .Text(value: "", placeholder: placeholder, validation: validation, editable: true)
  }

  /**
  pickerFormFieldTemplate:

  - parameter #context: NSManagedObjectContext

  - returns: FieldTemplate
  */
  static func pickerFormFieldTemplate(context context: NSManagedObjectContext,
                             optional: Bool = true,
                             editable: Bool = true) -> Field.Template
  {
    var allValues = allValuesForAttribute("name", context: context) as! [String]
    allValues.sortInPlace(<)
    let choices = optional ? ["None"] + allValues : allValues
    let initial = choices[0]
    return .Picker(value: initial, choices: choices, editable: editable)
  }

}
